name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'ebranda/flux-dev-controlnet'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve symbolic link to ComfyUI
        run: cp -R ../../comfyanonymous/ComfyUI ./

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}
